services:
  - type: web
    name: quicktask-backend
    runtime: java
    rootDir: quicktask-backend
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - fromGroup: quicktask-env

  - type: web
    name: quicktask-frontend
    runtime: node
    rootDir: quicktask-frontend
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --port 3000
    envVars:
      - fromGroup: quicktask-env
